/*
	This class is used to test callout web service
*/
@isTest
private class CSE_SOAP_WS_TEST {

	//@isTest static void testFlightCallout(){
	//	CSE_SOAPCREWONFLIGHT_WS flightcallout = new CSE_SOAPCREWONFLIGHT_WS();
	//	System.debug(flightcallout.getCrewonFlight('10Sep16', '0930', 'BKK', 'CDG'));
	//}

	//@isTest static void testFlightChangeCallout(){

	//}

	//@isTest static void testCrewOnFlightCallout(){
	//	CSE_SOAPCREWONFLIGHT_WS crewWs = new CSE_SOAPCREWONFLIGHT_WS();
	//	WS_CrewonFlightModel temp = crewWs.getCrewonFlight('10Sep16', '0930', 'BKK', 'CDG');
	//	List<Crew_List__c> crewlist = CrewonFlightService.getCrewListFromDataModel(temp, 'TG0930_10Sep16_1');
	//	for(Crew_List__c crew : crewlist){
	//		System.debug('Crew List: ' + crew);
	//	}
	//}

	//@isTest static void testRopProfileCallout(){

	//}

	//@isTest static void testRopMileageCallout(){

	//}

	//@isTest static void testRopAdditionalProfile(){

	//}
}